version: '3.3'
services:
  
  flask:
    build:
      context: ./flask
      dockerfile: flask.Dockerfile
    image: flask:nate.dev
    container_name: flask
    volumes:
      - type: bind
        source: ./flask
        target: /home/nate.dev
    expose:
      - "8080"
  
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    image: nginx:nate.dev
    container_name: nginx
    ports:
      - "80:80"
  
  mongodb:
    build:
      context: ./mongodb
      dockerfile: mongodb.Dockerfile
    image: mongodb:nate.dev
    container_name: mongodb
    volumes:
      - type: bind
        source: ./mongodb/db
        target: /data/db
